### ISSUE TITLE
Search function error returns incorrectly formatted JSON

### ISSUE THREAD

**Issue by matt-lindsay** [box/box-node-sdk#159]
Hi guys,

when executing the following function,
`client.search.query(filename, { type: 'folder' }, function (err, jsonData) { // ...do something });` and a folder with that name already exists, invalid JSON is being returned e.g.

`
{ Error: Unexpected API Response [409 Conflict] (item_name_in_use: "Item with the same name already exists")
    at Object.buildResponseError (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/box-node-sdk/lib/util/errors.js:57:23)
    at Object.buildUnexpectedResponseError (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/box-node-sdk/lib/util/errors.js:94:15)
    at /home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/box-node-sdk/lib/box-client.js:622:19
    at tryCatcher (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/promise.js:638:18)
    at /home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/bluebird/js/release/nodeback.js:42:21
    at BoxClient._handleResponse (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/box-node-sdk/lib/box-client.js:308:2)
    at handleResponseCallback (/home/ubuntu/workspace/box-scanned-docs-uploader/node_modules/box-node-sdk/lib/box-client.js:241:10)
  statusCode: 409,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'upload.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 701,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2233 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'upload.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 701,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2233 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { date: 'Wed, 26 Jul 2017 09:25:43 GMT',
        server: 'ATS',
        'content-type': 'application/json',
        'cache-control': 'no-cache, no-store',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        vary: 'Accept-Encoding',
        'content-length': '471',
        age: '0',
        connection: 'keep-alive' },
     rawHeaders: 
      [ 'Date',
        'Wed, 26 Jul 2017 09:25:43 GMT',
        'Server',
        'ATS',
        'Content-Type',
        'application/json',
        'Cache-Control',
        'no-cache, no-store',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains',
        'Vary',
        'Accept-Encoding',
        'Content-Length',
        '471',
        'Age',
        '0',
        'Connection',
        'keep-alive' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 409,
     statusMessage: 'Conflict',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'upload.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 701,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2233 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/2.0/files/content HTTP/1.1\r\nUser-Agent: Box Node.js SDK v1.7.0\r\nAuthorization: Bearer JSoTmeb1rjLN9KtfQERuMdRIPBxewzGS\r\nhost: upload.box.com\r\naccept: application/json\r\ncontent-type: multipart/form-data; boundary=--------------------------044794650448047235014794\r\ncontent-length: 380\r\nConnection: keep-alive\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/2.0/files/content',
        _ended: true,
        parser: null,
        timeoutCb: null,
        res: [Circular] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: true,
        agentClass: [Object],
        agentOptions: [Object],
        encoding: null,
        followRedirect: false,
        headers: [Object],
        method: 'POST',
        formData: [Object],
        timeout: 60000,
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: bound ],
        uri: [Object],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'upload.box.com',
        _form: [Object],
        path: '/api/2.0/files/content',
        _json: true,
        httpModule: [Object],
        agent: [Object],
        ntick: true,
        src: [Object],
        _started: true,
        href: 'https://upload.box.com/api/2.0/files/content',
        req: [Object],
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'upload.box.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 
      { type: 'error',
        status: 409,
        code: 'item_name_in_use',
        context_info: [Object],
        help_url: 'http://developers.box.com/docs/#errors',
        message: 'Item with the same name already exists',
        request_id: '90090560459786017a5c8c' } } }
`

I think that the 'Error' property might need encapsulating with quotes? Can this be resolved please? Thanks.

**Comment by matt-lindsay** [comment]
My mistake, the JSON is fine, it is coming from the `files.upload` function.
