### ISSUE TITLE
404 for Folders Metadata

### ISSUE THREAD

**Issue by seejamescode** [box/box-node-sdk#181]
Hello! After successfully getting service account‘s login information, I fail to get my folder‘s metadata. Do you have any pointers of what could be wrong with the code?

The code:
```
let configFile = JSON.parse(fs.readFileSync('config.json'));
let session = box.getPreconfiguredInstance(configFile);
let client = session.getAppAuthClient('enterprise');

client.users.get('me', null)
  .then((serviceAccountUser) => {
      console.log(serviceAccountUser.login) // This works
  })
  .catch((err) => {
      console.log(err);
  });

client.folders.get(
  '41012479206',
  {fields: 'name,shared_link,permissions,collections,sync_state'},
  (result) => {
    console.log(result);
  }
);
```

The output of result:
```
{ Error: Unexpected API Response [404 Not Found] (not_found: "Not Found")
    at Object.buildResponseError (/Users/jamesrauhut/ibm-repos/node_modules/box-node-sdk/lib/util/errors.js:57:23)
    at Object.buildUnexpectedResponseError (/Users/jamesrauhut/ibm-repos/node_modules/box-node-sdk/lib/util/errors.js:94:15)
    at /Users/jamesrauhut/ibm-repos/node_modules/box-node-sdk/lib/box-client.js:670:19
    at tryCatcher (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/jamesrauhut/ibm-repos/node_modules/bluebird/js/release/promise.js:582:21)
  statusCode: 404,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 283,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 283,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { date: 'Fri, 27 Oct 2017 19:37:28 GMT',
        'content-type': 'application/json',
        'content-length': '325',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'cache-control': 'no-cache, no-store',
        vary: 'Accept-Encoding',
        age: '0',
        connection: 'keep-alive' },
     rawHeaders:
      [ 'Date',
        'Fri, 27 Oct 2017 19:37:28 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '325',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains',
        'Cache-Control',
        'no-cache, no-store',
        'Vary',
        'Accept-Encoding',
        'Age',
        '0',
        'Connection',
        'keep-alive' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.box.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 283,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: false,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /2.0/folders/41012479206?fields=name%2Cshared_link%2Cpermissions%2Ccollections%2Csync_state HTTP/1.1\r\nUser-Agent: Box Node.js SDK v1.9.0 (Node v8.4.0)\r\nAuthorization: REDACTED\r\nhost: api.box.com\r\naccept: application/json\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/2.0/folders/41012479206?fields=name%2Cshared_link%2Cpermissions%2Ccollections%2Csync_state',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: true,
        agentClass: [Object],
        agentOptions: [Object],
        encoding: null,
        followRedirect: false,
        headers: [Object],
        method: 'GET',
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: bound ],
        uri: [Object],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.box.com',
        url: [Object],
        path: '/2.0/folders/41012479206?fields=name%2Cshared_link%2Cpermissions%2Ccollections%2Csync_state',
        _json: true,
        httpModule: [Object],
        agent: [Object],
        _started: true,
        href: 'https://api.box.com/2.0/folders/41012479206?fields=name%2Cshared_link%2Cpermissions%2Ccollections%2Csync_state',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'api.box.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body:
      { type: 'error',
        status: 404,
        code: 'not_found',
        context_info: [Object],
        help_url: 'http://developers.box.com/docs/#errors',
        message: 'Not Found',
        request_id: '201481866959f38af847337' } } }
```

**Comment by mattwiller** [comment]
Hi @seejamescode — are you sure that the folder belongs to the service account and not some other user?  Your code looks fine to me, and without more information, I can't really tell you why the API is giving you a 404 here.

In addition, be careful when posting full request object output like this — your original post contained your access token (which I edited out for you).  If you can, you should immediately revoke that token to ensure that nobody else who may have seen it can use it to access your content.

**Comment by seejamescode** [comment]
Ah, I think I got a bit closer because of your explanation. I added the service account as a co-owner of the folder. Now I get null instead of a 404. Is null the expected result?

**Comment by mattwiller** [comment]
Your code was using a callback but only taking one argument, so what you have as result here:
```
client.folders.get(
  '41012479206',
  {fields: 'name,shared_link,permissions,collections,sync_state'},
  (result) => {
    console.log(result);
  }
);
```
Is actually the error object; it being null is actually a good thing!  If you want to use a callback for this, you should change to something like this:
```
client.folders.get(
  '41012479206',
  {fields: 'name,shared_link,permissions,collections,sync_state'},
  (error, result) => {
    if (error) {
      console.log('An error happened!', error);
      return;
    }
    console.log(result);
  }
);
```

Alternatively, you can use promises like this:
```
client.folders.get(
  '41012479206',
  {fields: 'name,shared_link,permissions,collections,sync_state')
.then(result => console.log(result))
.catch(error => console.log('An error happened!', error));
```

**Comment by seejamescode** [comment]
Thank you!
