### ISSUE TITLE
App Auth Client: TypeError: key must be a string or buffer

### ISSUE THREAD

**Issue by louis-sanna** [box/box-node-sdk#185]
The following code returns an error when the upload function is called:

```
const BoxSDK = require("box-node-sdk");

const sdk = new BoxSDK(Object.assign({}, _config.box.boxAppSettings));

const appUserClient = sdk.getAppAuthClient("user", _config.box.userID);

exports.upload = function (path, options, next, callback) {
    appUserClient.files.uploadFile("0", null, path, function (err, file) {
        if (err) {
            next(new Error(err));
            return;
        }
        callback();
    });
};
```

Error:

```
err TypeError: key must be a string or buffer
    at typeError (/Users/louissanna/backend/node_modules/jwa/index.js:14:10)
    at Object.sign (/Users/louissanna/backend/node_modules/jwa/index.js:48:13)
    at Object.jwsSign [as sign] (/Users/louissanna/backend/node_modules/jws/lib/sign-stream.js:23:26)
    at Object.JWT.sign (/Users/louissanna/backend/node_modules/box-node-sdk/node_modules/jsonwebtoken/index.js:137:16)
    at TokenManager.getTokensJWTGrant (/Users/louissanna/backend/node_modules/box-node-sdk/lib/token-manager.js:316:20)
    at AppAuthSession._refreshAppAuthAccessToken (/Users/louissanna/backend/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:65:45)
    at AppAuthSession.getAccessToken (/Users/louissanna/backend/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:94:15)
    at BoxClient._makeRequest (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:264:27)
    at BoxClient.upload (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:568:14)
    at wrappedClientMethod (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:694:20)
    at Files.uploadFile (/Users/louissanna/backend/node_modules/box-node-sdk/lib/managers/files.js:532:63)
    at Object.exports.upload (/Users/louissanna/backend/modules/medias/box/lib.js:12:25)
    at uploadToService (/Users/louissanna/backend/modules/medias/upload.js:199:13)
    at Array.<anonymous> (/Users/louissanna/backend/modules/medias/upload.js:375:29)
    at Object.µ.execAll (/Users/louissanna/backend/utils/micro5.js:74:20)
    at /Users/louissanna/backend/modules/medias/upload.js:391:23
```

At this line: https://github.com/box/box-node-sdk/blob/master/lib/token-manager.js#L316 the argument keyParams is an object, but a lower level library (https://github.com/brianloveswords/node-jwa) seems to expect a buffer or string. I think using a newer version of jsonwebtoken  https://github.com/box/box-node-sdk/blob/master/package.json#L28 should fix the problem.

**Comment by mattwiller** [comment]
Hey @louis-sanna — it actually looks like this might be an error with your code.  Can you please check the value in your config object, specifically `_config.box.boxAppSettings.appAuth.privateKey`?  That's the value that this error is complaining about — it needs to be a string or a Buffer.

If you got your config from the Box Developer Console, the correct way to use that config blob with this SDK is like this:
```
const BoxSDK = require("box-node-sdk");
const sdk = BoxSDK.getPreconfiguredInstance(Object.assign({}, _config.box.boxAppSettings));
// everything else normally after this
```

**Comment by louis-sanna** [comment]
@mattwiller 

-  I checked and `console.log(typeof _config.box.boxAppSettings.appAuth.privateKey);` returns `string`.

- if I use getPreconfiguredInstance, I still get an error when I call `appUserClient.files.uploadFile `

```
TypeError: Cannot read property 'keyID' of undefined
    at TokenManager.getTokensJWTGrant (/Users/louissanna/backend/node_modules/box-node-sdk/lib/token-manager.js:291:34)
    at AppAuthSession._refreshAppAuthAccessToken (/Users/louissanna/backend/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:65:45)
    at AppAuthSession.getAccessToken (/Users/louissanna/backend/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:94:15)
    at BoxClient._makeRequest (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:264:27)
    at BoxClient.upload (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:568:14)
    at wrappedClientMethod (/Users/louissanna/backend/node_modules/box-node-sdk/lib/box-client.js:694:20)
    at Files.uploadFile (/Users/louissanna/backend/node_modules/box-node-sdk/lib/managers/files.js:532:63)
    at Object.exports.upload (/Users/louissanna/backend/modules/medias/box/lib.js:11:25)
    at uploadToService (/Users/louissanna/backend/modules/medias/upload.js:199:13)
    at Array.<anonymous> (/Users/louissanna/backend/modules/medias/upload.js:375:29)
    at Object.µ.execAll (/Users/louissanna/backend/utils/micro5.js:74:20)
    at /Users/louissanna/backend/modules/medias/upload.js:391:23
    at /Users/louissanna/backend/modules/medias/upload.js:69:13
    at /Users/louissanna/backend/node_modules/mv/index.js:34:26
    at FSReqWrap.oncomplete (fs.js:136:15)
```
 I added a console.log on this.config just before the error:

```
Config {
  _params: 
   { clientID: 'f0vi9rhjcgju185y6uhl6liekqfytpw8',
     clientSecret: 'TePUbiqagFzjoTo9evKVumq4tPGpssgy',
     apiRootURL: 'https://api.box.com',
     uploadAPIRootURL: 'https://upload.box.com/api',
     authorizeRootURL: 'https://account.box.com/api',
     apiVersion: '2.0',
     uploadRequestTimeoutMS: 60000,
     retryIntervalMS: 2000,
     numMaxRetries: 5,
     expiredBufferMS: 180000,
     staleBufferMS: 0,
     appAuth: undefined,
     iterators: false,
     enterpriseID: '33611434',
     request: 
      { strictSSL: true,
        agentClass: [Object],
        agentOptions: [Object],
        json: true,
        encoding: null,
        followRedirect: false,
        headers: [Object] } },
  clientID: 'f0vi9rhjcgju185y6uhl6liekqfytpw8',
  clientSecret: 'TePUbiqagFzjoTo9evKVumq4tPGpssgy',
  apiRootURL: 'https://api.box.com',
  uploadAPIRootURL: 'https://upload.box.com/api',
  authorizeRootURL: 'https://account.box.com/api',
  apiVersion: '2.0',
  uploadRequestTimeoutMS: 60000,
  retryIntervalMS: 2000,
  numMaxRetries: 5,
  expiredBufferMS: 180000,
  staleBufferMS: 0,
  appAuth: undefined,
  iterators: false,
  enterpriseID: '33611434',
  request: 
   { strictSSL: true,
     agentClass: { [Function: Agent] super_: [Object] },
     agentOptions: { keepAlive: true },
     json: true,
     encoding: null,
     followRedirect: false,
     headers: { 'User-Agent': 'Box Node.js SDK v1.10.0 (Node v8.6.0)' } } }
```

**Comment by mattwiller** [comment]
@louis-sanna Sorry about that, I deleted your comment because it had both your clientID and clientSecret in it — please be careful about posting data like that in public, since it could allow someone else to access your app!

You mentioned that `console.log(typeof _config.box.boxAppSettings.appAuth.privateKey);` returns `'string'`, which seems correct.  I'll look further into this in the morning!

**Comment by louis-sanna** [comment]
The error described in comment n°2 came the field `publicKeyID` I had renamed to `keyId`, so it no longer worked with `getPreconfiguredInstance`. Now I get the same error with `getPreconfiguredInstance` or without:
` TypeError: key must be a string or buffer`

**Comment by louis-sanna** [comment]
I modified manually the version of jws from 3.0.0 to 3.1.4 (which is a dependency of jsonwebtoken) and it works!

Would it be possible to upgrade `jsonwebtoken` to 8.1.0?

**Comment by mattwiller** [comment]
The version of `jsonwebtoken` we're using (5.7.0) is using `jws@^3.0.0`, which should include v3.1.4 already.  To test, I reinstalled the SDK and verified that it would use the correct version:
```
✔ ~/test 
11:24 $ npm ls jws
test@1.0.0 /Users/mwiller/test
└─┬ box-node-sdk@1.10.0
  └─┬ jsonwebtoken@5.7.0
    └── jws@3.1.4 
```

Could you try reinstalling `box-node-sdk` via npm and see if that resolves your issue?

**Comment by louis-sanna** [comment]
@mattwiller it's fixed, the problem came from npm. 

Thanks for your help.
