### ISSUE TITLE
TypeError: key must be a string or buffer

### ISSUE THREAD

**Issue by ovvn** [box/box-node-sdk#186]
Obtained json file with the structure:
```json
{
  "boxAppSettings": {
    "clientID": "xxx",
    "clientSecret": "xxx",
    "appAuth": {
      "publicKeyID": "xxx",
      "privateKey": "-----BEGIN ENCRYPTED PRIVATE KEY-----\\nxxx\\n-----END ENCRYPTED PRIVATE KEY-----\\n",
      "passphrase": "xxx"
    }
  },
  "enterpriseID": "xxx"
}
```
Trying to generate an enterprise access token according to
https://developer.box.com/v2.0/docs/authentication-with-jwt#section-3-generate-an-enterprise-access-token-with-box-sdks with the following code:
```coffeescript
    configFile = fs.readFileSync './config.json'   
    configFile = JSON.parse(configFile)

    session = BoxSDK.getPreconfiguredInstance configFile

    serviceAccountClient = session.getAppAuthClient('enterprise')
    serviceAccountClient.users.get('me', null)
      .then (serviceAccountUser) ->
        console.log {serviceAccountUser}

```

Getting the error:
```
Unhandled rejection TypeError: key must be a string or buffer
     at typeError (/app/node_modules/jwa/index.js:14:10)
     at Object.sign (/app/node_modules/jwa/index.js:48:13)
     at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:23:26)
     at Object.JWT.sign (/app/node_modules/box-node-sdk/node_modules/jsonwebtoken/index.js:137:16)
     at TokenManager.getTokensJWTGrant (/app/node_modules/box-node-sdk/lib/token-manager.js:316:20)
     at AppAuthSession._refreshAppAuthAccessToken (/app/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:65:45)
     at AppAuthSession.getAccessToken (/app/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:94:15)
     at BoxClient._makeRequest (/app/node_modules/box-node-sdk/lib/box-client.js:264:27)
     at BoxClient.get (/app/node_modules/box-node-sdk/lib/box-client.js:485:14)
     at wrappedClientMethod (/app/node_modules/box-node-sdk/lib/box-client.js:694:20)
     at Users.get (/app/node_modules/box-node-sdk/lib/managers/users.js:57:60)
     at checkInstructions (/app/build/webpack:/src/server/instructions/controller.coffee:49:32)
     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:76:5)
     at next (/app/node_modules/express/lib/router/route.js:100:13)
     at Route.dispatch (/app/node_modules/express/lib/router/route.js:81:3)
     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:76:5)
```

**Comment by ovvn** [comment]
Ok, looks like it's a problem with node/npm. On node v6.11.5 (npm v3.10.10) it works fine. The error occures in v8.9.1 (npm v5.5.1). Any ideas why it happens?

**Comment by mattwiller** [comment]
Hi @ovvn — we just had another report of a similar issue that was fixed by re-installing the SDK — it seems like the version of one of its dependencies gets messed up.  I'll see if I can dig in to see why this is happening, but in the meantime could you try reinstalling the SDK and let me know if that fixes the issue for you?

**Comment by ovvn** [comment]
Hi @mattwiller. Yes, if I switch to node v6.11.5 (npm v3.10.10) and reinstall all packages including the `box-node-sdk`, it works fine. If I reinstall modules in node v8.9.1 (npm v5.5.1) then the line throws:
```coffeescript
    serviceAccountClient.users.get('me', null).then (serviceAccountUser) ->
        console.log {serviceAccountUser}
```

**Comment by mattwiller** [comment]
Just to close the loop on this, we release v1.10.1 of the SDK, which should fix this issue.  If you still see this bug, please open another issue so we can continue investigating!
