### ISSUE TITLE
Error "Cannot read property 'headers' of undefined at cleanSensitiveHeaders"

### ISSUE THREAD

**Issue by neocolmartin** [box/box-node-sdk#299]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
From time to time we're seeing the error "Cannot read property 'headers' of undefined at cleanSensitiveHeaders".

It looks like for some reason, the `this.request` property that is passed into `cleanSensitiveHeaders` by `APIRequest._handleResponse`, despite the `bind()` call in `APIRequest.execute`.

I'm not sure if this is hiding another failure (e.g. error response from the server, or timeout) or whether this is causing an error when otherwise the call was successful. Looking at the stack trace I would guess that it might be an error that is occurring while constructing the request body, but if that is the case I think this cleanSensitiveHeaders error is causing the true error message to get lost.

### Versions Used
Node SDK: 1.19.0
Node.js: 6.14.3 (IBM SDK for Node.js)

### Steps to Reproduce
My code is calling `boxClient.folders.create`, `boxClient.folders.addMetadata` and `boxClient.files.uploadFile`. The file contents are provided as a either `Buffer` constructed from a string or a buffer provided by `express` with `multer` middleware from a HTTP file upload. I do not know which of these calls, or with which source of file data, the error is occurring.

### Error Message, Including Stack Trace
```
TypeError: Cannot read property 'headers' of undefined
    at cleanSensitiveHeaders (/home/vcap/app/node_modules/box-node-sdk/lib/api-request.js:148:16)
    at APIRequest._handleResponse (/home/vcap/app/node_modules/box-node-sdk/lib/api-request.js:240:2)
    at self.callback (/home/vcap/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at FormData.<anonymous> (/home/vcap/app/node_modules/request/request.js:1262:10)
    at emitOne (events.js:96:13)
    at FormData.emit (events.js:188:7)
    at FormData._error (/home/vcap/app/node_modules/form-data/lib/form_data.js:451:10)
    at FormData.append (/home/vcap/app/node_modules/form-data/lib/form_data.js:66:10)
    at appendFormValue (/home/vcap/app/node_modules/request/request.js:321:21)
    at Request.init (/home/vcap/app/node_modules/request/request.js:334:11)
    at new Request (/home/vcap/app/node_modules/request/request.js:128:8)
    at request (/home/vcap/app/node_modules/request/index.js:53:10)
    at APIRequest.execute (/home/vcap/app/node_modules/box-node-sdk/lib/api-request.js:208:18)
    at Promise.fromCallback.callback (/home/vcap/app/node_modules/box-node-sdk/lib/api-request-manager.js:49:53)
    at tryCatcher (/home/vcap/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/vcap/app/node_modules/bluebird/js/release/promise.js:180:30)
    at APIRequestManager.makeRequest (/home/vcap/app/node_modules/box-node-sdk/lib/api-request-manager.js:49:17)
    at promise._session.getAccessToken.then.accessToken (/home/vcap/app/node_modules/box-node-sdk/lib/box-client.js:316:33)
    at tryCatcher (/home/vcap/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vcap/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vcap/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/vcap/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/vcap/app/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/vcap/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/vcap/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@neocolmartin Thanks for letting us know!  Unfortunately, this may be somewhat difficult for us to reproduce, and hence to fix.  We'll try to take a look and see if we can think of any reason why this might be happening and test in our environment.

**Comment by mattwiller** [comment]
@neocolmartin We've been unable to find any promising leads on this issue so far — would you mind providing us a bit more information to help us debug?  If you could, please email me at the address in my GitHub profile and provide your client ID/API key (__NOT__ your client secret), and the exact date/time when you saw this problem happen.  We'll take a look in our server logs and try to find out what might have happened on the API side when this issue occurred.
