### ISSUE TITLE
Thrown messages for some API errors may need improvement

### ISSUE THREAD

**Issue by kachkaev** [box/box-node-sdk#307]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I was getting `Unexpected API Response [400 Bad Request]` in my enterprise app and could not figure out whether it was a problem with a JSON config, the server or something else. Here is my code:

```ts
const sdk = BoxSDK.getPreconfiguredInstance(boxConfig);
const client = sdk.getAppAuthClient("user", userId);
const items = await client.folders.getItems(boxFolderId);
```

Here's the look of the error stack:

```
Unexpected API Response [400 Bad Request]
    at Object.buildResponseError (/path/to/node_modules/box-node-sdk/lib/util/errors.js:96:23)
    at Object.buildUnexpectedResponseError (/path/to/node_modules/box-node-sdk/lib/util/errors.js:130:15)
    at requestManager.makeRequest.then.response (/path/to/node_modules/box-node-sdk/lib/token-manager.js:226:19)
    at tryCatcher (/path/to/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/node_modules/bluebird/js/release/promise.js:512:31)
    ...
```

Only after catching the error and adding `console.log(error.response.body)`, I saw: 

```js
{ error: 'unauthorized_client',
  error_description: 'This app is not authorized by the enterprise admin' }
```

It'd be great if [`lib/util/errors.js`](https://github.com/box/box-node-sdk/blob/master/lib/util/errors.js) was improved a bit and so that the stack trace became more informative by default. Just adding `console.log(error)` prints a massive object with enormous amounts of data and it is pretty hard to pinpoint the cause.

### Versions Used
Node SDK: 1.20.0
Node.js: 10.9.0

**Comment by kachkaev** [comment]
I guess a PR requires some knowledge about what possible shapes `error.response.body` may take. E.g. in `lib/util/errors.js` there is a mentioning of `response.body.message`, now there is at least `response.body.error`/`response.body.error_description` and there might be something else.

Given that, it might be probably better if someone from Box made a PR as you folks know API servers much better.
