### ISSUE TITLE
Javascript Error 

### ISSUE THREAD

**Issue by dcods22** [box/box-node-sdk#351]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.
I need to do very large bulk operations.  I consulted with Box on how to do this.  I thus create about 300 service workers and have them each do the bulk operation I need to do which is various different calls to multiple API endpoints. This process is done on about 55,000 files and takes a long time about 2 hours.  Randomly I get this error which I cannot reproduce too often besides running this job.

### Versions Used
Node SDK: // Replace with the version of the Node SDK you're using.  
Node.js: // Replace with the version of Node.js your application is running on.
1.25.0

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

Thu Feb 21 2019 14:11:08 GMT-0500 (EST) Error: TypeError: Cannot read property 'protocol' of undefined
    at new Request (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:41:20)
    at Object.buildResponseError (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:100:46)
    at Object.buildUnexpectedResponseError (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:130:15)
    at /Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/box-client.js:712:19
    at tryCatcher (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/nodeback.js:42:21
    at process.nextTick (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/api-request.js:342:3)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@dcods22 Thanks for letting us know!  I have a PR open to add a basic safety check in the code where this error is occurring (#353), which should unblock you for now.  I'm unsure what would cause this error, since it requires a request object with an undefined `uri` — we'll need to investigate a more thorough fix later.

**Comment by dcods22** [comment]
@mattwiller Thank you I saw the PR.  Do you know when that will be merged and the version will be released to NPM? This isn't super critical to our application but would be extremely helpful since we are sort of blocked for one specific flow based on this.  We (Major League Baseball) do have a Box Enterprise account

**Comment by mattwiller** [comment]
@dcods22 I just pushed out v1.26.2 of the SDK, which includes the fix for your issue.  Please try it out and let us know if you run into any further issues!
