### ISSUE TITLE
Javascript Error in Errors.js

### ISSUE THREAD

**Issue by dcods22** [box/box-node-sdk#357]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

This is a follow up of #351 that I posted on friday.  It seems the same requests also do not have a response which also throws an error.

Mon Feb 25 2019 10:38:26 GMT-0500 (EST) Error: TypeError: Cannot read property 'httpVersion' of undefined
    at new Request (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:51:33)
    at Object.buildResponseError (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:104:46)
    at Object.buildUnexpectedResponseError (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/util/errors.js:134:15)
    at /Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/box-client.js:712:19
    at tryCatcher (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/bluebird/js/release/nodeback.js:42:21
    at process.nextTick (/Users/dcody/Documents/projects/CLIPS2.0-Service/node_modules/box-node-sdk/lib/api-request.js:342:3)

### Versions Used
Node SDK: // Replace with the version of the Node SDK you're using.  
Node.js: // Replace with the version of Node.js your application is running on.

1.26.2

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by dcods22** [comment]
@mattwiller This is a follow up of #351

**Comment by mattwiller** [comment]
@dcods22 I put up a small PR to fix the immediate issue over at #359, but I'm a bit worried that we don't understand what the root cause is.  It seems like the SDK is in the "response error" flow when it has very little information about the request/response — I'm not sure why that would be happening.  I added another small change to split out potential error scenarios deeper in the SDK; maybe that might help get to the bottom of things?  If there's anything you can do to provide us more information about what's causing the original error you're seeing, that would be very helpful for us to address this in a broader way.

**Comment by dcods22** [comment]
@mattwiller I will try to get to the bottom of it it seems to be very weird.  We do an operation that makes ~5 API calls per operation.  We do that operation for reporting that goes over ~55,000 files using service workers.  Once we get to around ~35-40,000 files this error randomly appears and I would only get that error stack trace so it was extremely hard to debug what was going on. Do you know when the next SDK will be released so I can test this error and hopefully get to the bottom of this? Thanks for all of the help!

**Comment by mattwiller** [comment]
@dcods22 We have a release scheduled for tomorrow, I'll let you know when it goes out!

**Comment by mattwiller** [comment]
@dcods22 We just released v1.27.0 of the SDK, which includes the fix for this issue.  Please give it a try and let us know how it works!
