### ISSUE TITLE
TypeError: Cannot read property 'keyID' of undefined

### ISSUE THREAD

**Issue by yihchu** [box/box-node-sdk#394]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I want to create a folder, and it give me the error

### Versions Used
Node SDK: 1.29.0
Node.js: 10.13.0

### Steps to Reproduce

I created an application, and set OAuth2 with JWT, then download the json. And the code is: 
const boxSDK = require('box-node-sdk');  // Box SDK
const fs = require('fs');                // File system for config

// Fetch config file for instantiating SDK instance
const configJSON = JSON.parse(fs.readFileSync('config.json'));

// Instantiate instance of SDK using generated JSON config
const sdk = boxSDK.getPreconfiguredInstance(configJSON);

// Create auth client
const client = sdk.getAppAuthClient('enterprise', configJSON.enterpriseID);

// PERFORM API ACTIONS WITH CLIENT
//

client.folders.create(0, 'Auto-Test', () => {})

### Error Message, Including Stack Trace
/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/token-manager.js:301
		if (!this.config.appAuth.keyID) {
		                         ^

TypeError: Cannot read property 'keyID' of undefined
    at TokenManager.getTokensJWTGrant (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/token-manager.js:301:28)
    at AppAuthSession._refreshAppAuthAccessToken (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:86:45)
    at AppAuthSession.getAccessToken (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:138:15)
    at BoxClient._makeRequest (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/box-client.js:295:27)
    at BoxClient.post (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/box-client.js:540:14)
    at wrappedClientMethod (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/box-client.js:734:20)
    at Folders.create (/Users/yihchu/Code/Sublime/BoxTest/node_modules/box-node-sdk/lib/managers/folders.js:113:61)
    at Object.<anonymous> (/Users/yihchu/Code/Sublime/BoxTest/test.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@yihchu Your code __should__ work; this looks like it might be an issue with the configuration file you're using.  Could you verify that `configJSON` in your code is an object that looks roughly like this?
```js
{
  boxAppSettings: {
    clientID: "YOUR CLIENT ID",
    clientSecret: "YOUR CLIENT SECRET",
    appAuth: {
      publicKeyID: "YOUR KEY ID",
      privateKey: "YOUR PRIVATE KEY",
      passphrase: "YOUR PASSPHRASE"
    }
  },
  enterpriseID: "YOUR ENTERPRISE ID",
}
```

**Comment by yihchu** [comment]
3Q~,  I forgot to generate private key.
