### ISSUE TITLE
Box getReadStream error: Error: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by iamrahulroy** [box/box-node-sdk#502]
- [ x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
It keeps throwing `error:0909006C:PEM routines:get_name:no start line` error. I've tested the snippet locally and it is working.

### Versions Used
Node SDK: 1.31.0
Node.js: 12.x

### Steps to Reproduce
Code sample:
```
const sdk = new BoxSDK({
  clientID: process.env.BOX_CLIENT_ID,
  clientSecret: process.env.BOX_CLIENT_SECRET,
  appAuth: {
    keyID: process.env.JWT_PUBLIC_KEY_ID,
    privateKey: process.env.JWT_PRIVATE_KEY,
    passphrase: process.env.JWT_PRIVATE_KEY_PASSWORD
  }
});
// ...
client.files.getReadStream(fileID, null, function(error, stream) {
  if (error) {
    console.log('Box getReadStream error:', error) // throws error here..
  }

  const outputFilePath = `/tmp/${filename}`;
  const output = fs.createWriteStream(outputFilePath);
  stream.pipe(output);

  stream.on('end', () => {
    resolveDownload();
  });
});
```

### Error Message, Including Stack Trace
```
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:105:29)
    at Object.sign (/var/task/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/var/task/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/var/task/node_modules/jsonwebtoken/sign.js:204:16)
    at TokenManager.getTokensJWTGrant (/var/task/node_modules/box-node-sdk/lib/token-manager.js:350:20)
    at AppAuthSession._refreshAppAuthAccessToken (/var/task/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:86:45)
    at AppAuthSession.getAccessToken (/var/task/node_modules/box-node-sdk/lib/sessions/app-auth-session.js:138:15)
    at BoxClient._makeRequest (/var/task/node_modules/box-node-sdk/lib/box-client.js:295:27)
    at BoxClient.get (/var/task/node_modules/box-node-sdk/lib/box-client.js:526:14)
    at Files.getDownloadURL (/var/task/node_modules/box-node-sdk/lib/managers/files.js:186:21)
    at Files.getReadStream (/var/task/node_modules/box-node-sdk/lib/managers/files.js:240:14)
    at /var/task/src/libs/box.js:26:20
    at new Promise (<anonymous>)
    at Box.downloadFile (/var/task/src/libs/box.js:10:12)
    at downloadFromSource (/var/task/src/libs/helpers.js:10:27)
    at /var/task/src/libs/handleConversion.js:13:29 {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

It looks like a formatting issue. Also, in the following code, for downloading a file, box is returning blank stream.
```
var fs = require('fs');
client.files.getReadStream('12345', null, function(error, stream) {

	if (error) {
		// handle error
	}

	// write the file to disk
	var output = fs.createWriteStream('/path/to/file');
	stream.pipe(output);
});
```

**Comment by sujaygarlanka** [comment]
@iamrahulroy This issue probably has to do with how you are importing your private key. A possible solution is described [here](https://github.com/auth0/node-jsonwebtoken/issues/642#issuecomment-585173594). The solution recommended in this post is to replace `process.env.JWT_PRIVATE_KEY` with `process.env.JWT_PRIVATE_KEY.replace(/\\n/gm, '\n')`.

**Comment by iamrahulroy** [comment]
@sujaygarlanka thanks for the response. I dug into SDK codebase and implemented an alternate method. Instead of importing the key as an environment variable, I imported it as a file and it worked like a charm. 

I'll try the suggested solution next week and report back. Thanks again!
