### ISSUE TITLE
econnreset failure is not handled by SDK retry logic

### ISSUE THREAD

**Issue by lukesiler** [box/box-node-sdk#512]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
We use a few files and folders API's.  Each of them can fail with ECONNRESET when a TCP connection is lost or reset.  The built-in retry logic does not handle these communication failures so we have to write our own retry logic which works fine.

### Steps to Reproduce
1. Run the following API calls consistently over several days
- files.get
- files.getReadStream
- folders.getItems

### Expected Behavior
Built-in request retry logic should catch and retry ECONNRESET

`
if (boxErr && boxErr.code && boxErr.code === 'ECONNRESET') {
  // retry request
}
`

### Error Message, Including Stack Trace

`
{
   code: "ECONNRESET"    
   message: "socket hang up"    
   name: "Error"    
   stack: "Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.socketOnEnd (_http_client.js:440:23)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"    
  }
`

### Versions Used
Node SDK: 1.32.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukesiler** [comment]
@PJSimon - another interesting note here.  I've been chasing an intermittent bug in files.getReadStream where it sometimes just stalls out.  This turns out to be caused by an ECONNRESET that occasionally happens.

` 
  err: {
   code: "ECONNRESET"    
   message: "socket hang up"    
   name: "Error"    
   stack: "Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.socketOnEnd (_http_client.js:440:23)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"    
  }
`

**Comment by lukesiler** [comment]
hi @PJSimon,

I also found that 503 error is not being handled by built-in retry code.

`err: {
   message: "503 - Service Unavailable"    
   name: "Error"    
   stack: "Error: 503 - Service Unavailable
    at APIRequest._handleResponse (/opt/pryon/contapp/node_modules/box-node-sdk/lib/api-request.js:234:9)
    at Request.self.callback (/opt/pryon/contapp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/opt/pryon/contapp/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/opt/pryon/contapp/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"    
  }`

It would be great if sdk retry handled both ECONNRESET and 503.

thanks,
@lukesiler
