### ISSUE TITLE
What to set as callback when to retrieve enterprise events.

### ISSUE THREAD

**Issue by kondonator** [box/box-node-sdk#540]
Hi.
I'm trying to gather all enterprise events and write them into a log file via nodejs.
I have read [api reference](https://developer.box.com/reference/get-events/) and added some code based on the api reference but it logged nothing but 'Hello XXX!'.

The [api reference](https://developer.box.com/reference/get-events/#request) described to call `client.events.get({stream_position: '1408838928446360'}, callback);` for Node but I have no idea what to replace 'callback' into.
How should I call to retrieve an enterprise events?

Thanks in advance.
```
module.exports = async function (context, myTimer) {
    var BoxSDK = require('box-node-sdk');

    var sdkConfig = require('../box/config.json');
    var sdk = BoxSDK.getPreconfiguredInstance(sdkConfig);

    // Get the service account client, used to create and manage app user accounts
    // The enterprise ID is pre-populated by the JSON configuration,
    // so you don't need to specify it here
    var client = sdk.getAppAuthClient('enterprise');

    if (myTimer.isPastDue)
    {
        context.log('JavaScript is running late!');
    }

    // Get your own user object from the Box API
    // All client methods return a promise that resolves to the results of the API call,
    // or rejects when an error occurs
    client.users.get(client.CURRENT_USER_ID)
        .then(user => console.log('Hello', user.name, '!'))
        .catch(err => console.log('Got an error!', err));

    client.events.get({limit: 10, stream_position: 0, stream_type: 'admin_logs'}, function(response) {
        console.log(response);
    });
};
```

**Comment by sujaygarlanka** [comment]
@kondonator I would take a look at the docs here https://github.com/box/box-node-sdk/blob/master/docs/events.md#events. Feel free to re-open this issue if you have any follow up questions.

**Comment by kondonator** [comment]
Hi.
My goal is to make an application that is to export the users activities report into the file.
Now this is done by the user's manual operation periodically but we want to make it by the application ran by cron.

Now that I may know that this is done by calling the followings to retrieve logs :
https://github.com/box/box-node-sdk/blob/master/docs/events.md#user-events
https://github.com/box/box-node-sdk/blob/master/docs/events.md#enterprise-events

The client is the enterprise user.
I asked my client to register us as a user and we already confirmed that we also could generate the users activities report from the browser.
We are entitled to create an application from the browser and we are also registered as a collaborator.
We have created the simple application that is to retrieve groups, event stream ,and enterprise event stream as follows:

```
const BoxSDK = require('box-node-sdk');

const sdkConfig = require('./enterprise_config.json'); // Read the authentication file
const sdk = BoxSDK.getPreconfiguredInstance(sdkConfig);
const client = sdk.getAppAuthClient('enterprise');

getGroups();
getEventStream();
getEnterpriseEventStream();

function getGroups() {
    client.groups.getAll()
        .then(groups => {
            for(const group of groups.entries) {
                console.log(group.name);
            }
        });
}

function getEventStream() {
    client.events.getEventStream(function(err, stream) {
        if (err) {
            // handle error
            console.error(err);
        }

        else {
            stream.on('data', function(event) {
                // handle the event
                console.log(event);
            });
        }
    });
}

function getEnterpriseEventStream() {
    client.events.getEnterpriseEventStream(function(err, stream) {
        if (err) {
            // Handle error
            console.error(err);
        }
        else {
            stream.on('data', function(event) {
                // Handle the event
                console.log(event);
            });
        }
    });
}
```

I ran this application.
getGroups() works and displays the name of groups.
getEnterpriseEventStream() displays nothing.
getEventStream() throws exception of 403 Forbidden

```
> node script.js
Error: Unexpected API Response [403 Forbidden | wmbhxygmv53ccbv1.08a3f4fb3205574063ac159693ad2b537] forbidden - Forbidden
    at Object.buildResponseError (C:\Users\Kondo\Development\20201221\node_modules\box-node-sdk\lib\util\errors.js:120:23)
    at Object.buildUnexpectedResponseError (C:\Users\Kondo\Development\20201221\node_modules\box-node-sdk\lib\util\errors.js:154:15)
    at C:\Users\Kondo\Development\20201221\node_modules\box-node-sdk\lib\managers\events.js:76:18
    at tryCatcher (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._settlePromise (C:\Users\Kondo\Development\20201221\node_modules\bluebird\js\release\promise.js:617:21) {
  statusCode: 403,
```

I think the RSA key pair is correctly loaded that is because I could retrieve groups via BOX api.
So calling getEventStream() and getEnterpriseEventStream() are beyond getGroups().

Question:
**Which point I should check and what it is to be?**
