### ISSUE TITLE
Expired Auth error on non-expiring App Token when deploying to production - GCP

### ISSUE THREAD

**Issue by shekharsaxena** [box/box-node-sdk#571]
- [y] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [y] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [y] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [y] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am using the basicClient with a never expiring token to set up my box client on Node:

`
var sdk = new BoxSDK({
    clientID: `${process.env.BOX_CLIENT}`,
    clientSecret: '',
});

const client = sdk.getBasicClient(process.env.BOX_TOKEN);`

And I am able to get both embed and download URLs locally in my development environment with a local environment variable for the BOX_TOKEN. However, when I deploy to GCP, I keep getting the following errors (even though I have set the proper BOX_TOKEN in my production secrets): Expired Auth: Auth code or refresh token has expired

I am using the same token with a rails backend on GCP (using the Box gem for rails) and it is working fine.

### Steps to Reproduce
Deploy to GCP and when calling a function that tries to use the API to get an embed link `client.files.getEmbedLink(boxUploadId);`  Get the errors above

### Expected Behavior
Able to use API without it throwing an error about the token being expired (given that it is a never expiring token)

### Error Message, Including Stack Trace
`Error: Expired Auth: Auth code or refresh token has expired [401 Unauthorized | .0e4b406acf7dcc138ab7e055d3a9bf4f3]      at Object.buildResponseError (/app/node_modules/box-node-sdk/lib/util/errors.js:120:23)      at Object.buildAuthError (/app/node_modules/box-node-sdk/lib/util/errors.js:139:28)      at /app/node_modules/box-node-sdk/lib/box-client.js:336:37      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)      at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:617:21)      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)      at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)      at /app/node_modules/bluebird/js/release/nodeback.js:42:21      at /app/node_modules/box-node-sdk/lib/api-request.js:335:3      at processTicksAndRejections (internal/process/task_queues.js:79:11) 

{
    statusCode: 401,
    response: IncomingMessage {
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrainWriters: null,
        multiAwaitDrain: false,
        readingMore: true,
        decoder: null,
        encoding: null,
        [Symbol(kPaused)]: false
      },
      readable: false,
      _events: [Object: null prototype] {
        end: [Array],
        close: [Array],
        data: [Function],
        error: [Function]
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: true,
        _SNICallback: null,
        servername: 'api.box.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'api.box.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        timeout: 0,
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(asyncId)]: -1,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object]
      },
      connection: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: true,
        _SNICallback: null,
        servername: 'api.box.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'api.box.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        timeout: 0,
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(asyncId)]: -1,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object]
      },
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: {
        date: 'Fri, 26 Feb 2021 04:53:05 GMT',
        'transfer-encoding': 'chunked',
        connection: 'keep-alive',
        'x-envoy-upstream-service-time': '1',
        'strict-transport-security': 'max-age=31536000',
        'www-authenticate': 'Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."',
        'box-request-id': '0e4b406acf7dcc138ab7e055d3a9bf4f3'
      },
      rawHeaders: [
        'Date',
        'Fri, 26 Feb 2021 04:53:05 GMT',
        'Transfer-Encoding',
        'chunked',
        'Connection',
        'keep-alive',
        'x-envoy-upstream-service-time',
        '1',
        'Strict-Transport-Security',
        'max-age=31536000',
        'www-authenticate',
        'Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."',
        'BOX-REQUEST-ID',
        '0e4b406acf7dcc138ab7e055d3a9bf4f3'
      ],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: true,
        _SNICallback: null,
        servername: 'api.box.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'api.box.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        timeout: 0,
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(asyncId)]: -1,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object]
      },
      _consuming: false,
      _dumped: false,
      req: ClientRequest {
        _events: [Object: null prototype],
        _eventsCount: 5,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'GET /2.0/files/780659369211?fields=expiring_embed_link HTTP/1.1\r\n' +
          'User-Agent: Box Node.js SDK v1.36.0 (Node v12.19.0)\r\n' +
          'Authorization: Bearer undefined\r\n' +
          'X-Box-UA: agent=box-node-sdk/1.36.0; env=Node/12.19.0\r\n' +
          'host: api.box.com\r\n' +
          'accept: application/json\r\n' +
          'Connection: keep-alive\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        method: 'GET',
        insecureHTTPParser: undefined,
        path: '/2.0/files/780659369211?fields=expiring_embed_link',
        _ended: true,
        res: [Circular],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'api.box.com',
        protocol: 'https:',
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype]
      },
      request: Request {
        _events: [Object: null prototype],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: true,
        agentClass: [Function: Agent],
        agentOptions: [Object],
        encoding: null,
        followRedirect: false,
        headers: [Object],
        method: 'GET',
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: bound ],
        uri: [Url],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.box.com',
        url: [Url],
        path: '/2.0/files/780659369211?fields=expiring_embed_link',
        _json: true,
        httpModule: [Object],
        agent: [Agent],
        _started: true,
        href: 'https://api.box.com/2.0/files/780659369211?fields=expiring_embed_link',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: 'api.box.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _ended: true,
        _callbackCalled: true,
        [Symbol(kCapture)]: false
      },
      toJSON: [Function: responseToJSON],
      caseless: Caseless { dict: [Object] },
      [Symbol(kCapture)]: false
    },
    request: Request {
      method: 'GET',
      url: {
        protocol: 'https:',
        host: 'api.box.com',
        path: '/2.0/files/780659369211',
        query: [Object: null prototype],
        fragment: null
      },
      httpVersion: '1.1',
      headers: {
        'User-Agent': 'Box Node.js SDK v1.36.0 (Node v12.19.0)',
        Authorization: '[REMOVED BY SDK]',
        'X-Box-UA': 'agent=box-node-sdk/1.36.0; env=Node/12.19.0',
        accept: 'application/json'
      },
      body: undefined
    },
    authExpired: true
  }`

### Versions Used
Node SDK: 1.36.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by shekharsaxena** [comment]
I was able to get around this by making an axios call directly to the box api in my node backend instead of using the node sdk.
