### ISSUE TITLE
Upload and Upload New Version aren't working (404 Not Found)

### ISSUE THREAD

**Issue by mathmul** [box/box-node-sdk#794]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

The main problem is that uploading does not work while everything else is. Details below.

Having a Node / ExpressJS app written in TypeScript and a Box application with Client Credentials Grant using App Access, I have build a Box API for our backend to use with a managed user access (The user has Editor rights for all folders/files in question. I tried not setting any CORS domains, and also setting them like this: `http://localhost:3000, http://127.0.0.1:3000, http://localhost, http://127.0.0.1, https://localhost:3000, https://127.0.0.1:3000, https://localhost, https://127.0.0.1`
- [X] Successfully created a CCG Client for our User
- [X] Successfully tested the following
    - getFolderInfo
    - getFolderItems
    - createFolder
    - getFileInfo
    - getFileDownloadUrl
    - downloadFile
- [X] UNsuccessfully tested the following
    - uploadFile
    - uploadNewVersionOfFile
    
In both unsuccessful attempts, the response displayed in the web browser is:
```
Error: Unexpected API Response [404 Not Found]
    at Object.buildResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:125:40)
    at Object.buildUnexpectedResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:160:15)
    at /app/node_modules/box-node-sdk/src/box-client.ts:756:20
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/app/node_modules/bluebird/js/release/nodeify.js:23:30)
    at bound (domain.js:427:14)
    at Promise.runBound [as _fulfillmentHandler0] (domain.js:440:12)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
```

### Steps to Reproduce
My API implementation:
```typescript
import BoxSDK from 'box-node-sdk';
import BoxClient from 'box-node-sdk/lib/box-client';
import config from './config';
import fs from "fs";
import log from "./log";

export default class Box {

    client: BoxClient;

    constructor() {
        this.client = this.getBoxClient();
    }

    async test() {
        console.log('\n>>> in test');
        const folder = {
            apiExperiments: {
                id: '188708936015',
                files: {
                    lion: '1105071149026'
                }
            },
        };
        return {
            folderInfo: await this.getFolderInfo(folder.apiExperiments.id),
            folderItems: await this.getFolderItems(folder.apiExperiments.id),
            fileInfo: await this.getFileInfo(folder.apiExperiments.files.lion),
            fileDownloadUrl: await this.getFileDownloadUrl(folder.apiExperiments.files.lion),
            downloadFileStream: await this.downloadFile(folder.apiExperiments.files.lion, 'src/lion.jpg'),
            // createFolder: await this.createFolder('test', folder.apiExperiments.id), // new folder id: 189415022685
            // ABOVE WORK, BELOW FAIL
            uploadFile: await this.uploadFile('src/x.png', 'y.png', folder.apiExperiments.id),
            uploadNewVersionOfFile: await this.uploadNewVersionOfFile(folder.apiExperiments.files.lion, 'src/x.png'),
        };
    }

    private async getFileInfo(fileId: string, fields: Array<string>|null = null): Promise<string> {
        log.writeInfo("Downloading file information from Box...", { fileId });

        const options = fields === null
            ? undefined
            : { fields: fields.join(',') };

        return await this.client
            .files
            .get(
                fileId,
                options,
                this.logErrorCallback("Error downloading file from Box")
            );
    }

    public async downloadFile(fileId: string, filePath: string): Promise<any> {
        log.writeInfo("Downloading file stream from Box...", { fileId });

        return await this.client
            .files
            .getReadStream(
                fileId,
                undefined,
                (error: any, stream: any) => {
                    if (error) {
                        log.writeError("Error downloading file from Box", { err: error });
                        throw error;
                    }

                    const output = fs.createWriteStream(filePath);
                    stream.pipe(output);
                }
            );
    }

    private async getFileDownloadUrl(fileId: string): Promise<string> {
        log.writeInfo("Getting file download URL from Box...", { fileId });

        return await this.client
            .files
            .getDownloadURL(
                fileId,
                undefined,
                this.logErrorCallback("Error getting file download URL from Box")
            );
    }

    public async uploadFile(filePath: string, fileName: string, folderId: string): Promise<any> {
        log.writeInfo("Uploading file to Box...", { folderId, fileName, filePath });

        const stream = fs.createReadStream(filePath);

        return await this.client
            .files
            .uploadFile(
                folderId,
                fileName,
                stream,
                undefined,
                this.logErrorCallback("Error uploading file to Box")
            );
    }

    private async uploadNewVersionOfFile(fileId: string, filePath: string): Promise<any> {
        log.writeInfo("Uploading new version of file to Box...", { fileId });

        const stream = fs.createReadStream(filePath);

        return await this.client
            .files
            .uploadNewFileVersion(
                fileId,
                stream,
                undefined,
                (error: any, file: any) => {
                    if (error) {
                        log.writeError("Error uploading new version of file to Box", { err: error });
                        throw error;
                    }

                    log.writeInfo("New version of file uploaded to Box", { file });
                }
            );
    }

    /**
     * @param fields - Array of fields to return. If null, all fields will be returned. Available fields: type, id,
     * sequence_id, etag, name, created_at, modified_at, description, size, path_collection, created_by,
     * modified_by, owned_by, shared_link, parent, item_status, item_collection
     */
    private async getFolderInfo(folderId: string, fields: Array<string>|null = null): Promise<any> {
        log.writeInfo("Getting folder info from Box...", { folderId });

        const options = fields === null
            ? undefined
            : { fields: fields.join(',') };

        return await this.client
            .folders
            .get(
                folderId,
                options,
                this.logErrorCallback("Error getting folder info from Box")
            );
    }

    private async getFolderItems(folderId: string, options?: object|undefined): Promise<any> {
        log.writeInfo("Getting folder items from Box...", { folderId });

        return await this.client
            .folders
            .getItems(
                folderId,
                options,
                this.logErrorCallback("Error getting folder items from Box")
            );
    }

    private async createFolder(folderName: string, parentFolderId: string|null): Promise<any> {
        log.writeInfo("Creating folder in Box...", { folderName });

        return await this.client
            .folders
            .create(
                parentFolderId ?? config.box.designatedFolderId,
                folderName,
                this.logErrorCallback("Error creating folder in Box")
            );
    }

    private logErrorCallback(message: string): Function {
        return (err: any, res: any) => {
            if (err) {
                log.writeError(message, { err });
                throw err;
            }
        }
    }

    private getBoxClient(): BoxClient {
        const sdk = BoxSDK.getPreconfiguredInstance({
            boxAppSettings: {
                clientID: 'CLIENT_ID',
                clientSecret: 'CLIENT_SECRET',
            },
        });
        sdk.configure({
            apiRootURL: 'https://CLIENT.app.box.com/api',
            uploadAPIRootURL: 'https://CLIENT.app.box.com/upload',
            authorizeRootURL: 'https://CLIENT.app.box.com/account',
        });

        return sdk.getCCGClientForUser('USER_ID');
    }
}

```

### Expected Behavior
New file should be uploaded and an existing file should be updated including a version bump

### Error Message, Including Stack Trace
```cli
>>> in test
{"fileName":"y.png","filePath":"src/x.png","folderId":"188708936015","level":"info","message":"Uploading file to Box...","timestamp":"2023-01-09 12:01:22"}
{"err":{"request":{"headers":{"Authorization":"[REMOVED BY SDK]","User-Agent":"Box Node.js SDK v2.8.0 (Node v12.22.12)","X-Box-UA":"agent=box-node-sdk/2.8.0; env=Node/12.22.12","accept":"application/json","content-length":1236,"content-type":"multipart/form-data; boundary=--------------------------451488114424587601557599"},"httpVersion":"1.1","method":"POST","url":{"fragment":null,"host":"CLIENT.app.box.com","path":"/upload/2.0/files/content","protocol":"https:","query":{}}},"response":{"headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","content-type":"text/html; charset=UTF-8","date":"Mon, 09 Jan 2023 12:01:27 GMT","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","via":"1.1 google"},"request":{"headers":{"Authorization":"[REMOVED BY SDK]","User-Agent":"Box Node.js SDK v2.8.0 (Node v12.22.12)","X-Box-UA":"agent=box-node-sdk/2.8.0; env=Node/12.22.12","accept":"application/json","content-length":1236,"content-type":"multipart/form-data; boundary=--------------------------451488114424587601557599"},"method":"POST","uri":{"auth":null,"hash":null,"host":"CLIENT.app.box.com","hostname":"CLIENT.app.box.com","href":"https://CLIENT.app.box.com/upload/2.0/files/content","path":"/upload/2.0/files/content","pathname":"/upload/2.0/files/content","port":443,"protocol":"https:","query":null,"search":null,"slashes":true}},"statusCode":404},"statusCode":404},"level":"error","message":"Error uploading file to Box","timestamp":"2023-01-09 12:01:24"}
(node:74) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(node:74) UnhandledPromiseRejectionWarning: Error: Unexpected API Response [404 Not Found]
    at Object.buildResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:125:40)
    at Object.buildUnexpectedResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:160:15)
    at /app/node_modules/box-node-sdk/src/box-client.ts:791:19
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/app/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:730:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
(node:74) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Unexpected API Response [404 Not Found]
    at Object.buildResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:125:40)
    at Object.buildUnexpectedResponseError (/app/node_modules/box-node-sdk/src/util/errors.ts:160:15)
    at /app/node_modules/box-node-sdk/src/box-client.ts:756:20
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/app/node_modules/bluebird/js/release/nodeify.js:23:30)
    at bound (domain.js:427:14)
    at Promise.runBound [as _fulfillmentHandler0] (domain.js:440:12)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
```

### Versions Used
package.json: `"box-node-sdk": "^2.8.0"`

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-node-sdk/search?type=Issues

**Comment by mathmul** [comment]
Apparently while I was correct to set API and Account URL, I should not have done so for Upload. Removing the line from `getBoxClient` resolved the issue.
